# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='file',
            name='modified_on',
        ),
    ]
